Add run_dbcommand logic ported from Fastmail code
cyrusimap/cassandane pull request #150
Opened 2021-08-23 13:58 UTC by brong

This was SUPPOSED to be a small metadata test, and turned into realising that all of the Metadata tests weren't actually working correctly, because list_annotations wasn't doing what it said on the tin for two separate bugs - but comparing the replication still got us zero / zero annotations, which funnily enough passed the tests.

Doing things this way gives us a much more powerful ability to manipulate database files.

2021-08-25 02:17 UTC, elliefm requested changes
There's a bunch of two-space indents in here, and while Cassandane is mostly four space indents, there are already a bunch of two-space indents elsewhere.  I think it's a difference between Fastmail perl style and Cyrus-project style, and Fastmail perl style sometimes slipping in.

I might usually let it slide since Cassandane is already a bit of a shambles, but given that we're planning on moving it into the cyrus-imapd repo, and will probably want to unify on the-same-as-Cyrus, it'd be nice to not introduce more mess to have to tidy up later!

2021-08-25 02:17 UTC, elliefm commented on Cassandane/Cyrus/Metadata.pm
> +    $format = $format // 'twoskip';
Ah I see, it looks like at some point annotation_db went from defaulting to 'skiplist' to defaulting to 'twoskip' and the test was never updated to match...

Assuming that in the future, the default will eventually change from twoskip to something else, can we do something here such that if the test has not been updated to match, it fails, so we can catch it right away?

2021-08-31 13:41 UTC, brong commented on Cassandane/Instance.pm
> +  my ($linecb, $dbname, $engine, @items) = @_;
Yeah, it's used in other functions nearby, so I copied it.

2021-08-31 13:43 UTC, brong commented on Cassandane/Instance.pm
> +  LINE: while (defined(my $line = <FH>)) {
It's hand-written, but extracted from a Fastmail homegrown tool originally.  It's a horror show which works against a build on x86_64.  The format is really bad and build dependent, but short of writing a C util to parse the thing, that's what we've got.

2021-08-31 13:45 UTC, brong commented on Cassandane/Cyrus/Rename.pm
> +    ));
oh - it should be caps.  BATCH MODE is actually case significant.

2021-08-31 13:45 UTC, brong commented on Cassandane/Cyrus/Metadata.pm
> +    $format = $format // 'twoskip';
I'd like to change the tool to not require a format at all, and the cyrusdb layer to do format detection if nothing is passed!

2021-08-31 13:47 UTC, brong commented on Cassandane/Cyrus/Rename.pm
> +    ));
yeah - the command line commands are lower case, but the batch mode are upper.  Good catch.  `delete` would have errored out and/or silently been ignored.

```
            else {
                r = IMAP_MAILBOX_NONEXISTENT;
                goto done;
            }
```
Yeah, errored.  I guess we never used that.

2021-08-31 13:53 UTC, brong commented on Cassandane/Instance.pm
> +  my ($linecb, $dbname, $engine, @items) = @_;
I changed it to the my (...) style :)

The purpose of this structure is that `$self->foo(@args)` shifts `$self` but leaves all of `@args` in `@_`

2021-08-31 13:56 UTC, brong commented
All requested changes added :)

2021-09-01 02:59 UTC, elliefm approved these changes

2021-09-05 23:45 UTC, merged