JMAPEmail: include Trash unseen counts in threadKeyword search
cyrusimap/cassandane pull request #180
Opened 2021-10-28 12:50 UTC by rsto

2021-11-01 04:09 UTC, elliefm requested changes

2021-11-01 04:09 UTC, elliefm commented on Cassandane/Cyrus/JMAPEmail.pm
> +    if ($maj < 3 || $min < 5) {
```suggestion
    if ($maj < 3 || ($maj == 3 && $min < 5)) {
```

Otherwise this condition will fire wrong for e.g. 4.2

2021-11-02 07:13 UTC, rsto commented on Cassandane/Cyrus/JMAPEmail.pm
> +    if ($maj < 3 || $min < 5) {
Thanks. I amended the original commit, I had to rebase to the main branch anyway.

2021-11-22 08:20 UTC, rsto commented
Merged into cyrus-imapd repo at https://github.com/cyrusimap/cyrus-imapd/pull/3730/commits/6c9df52912d7aa13358fd3daf2c1b8bc048598ed

2021-11-22 08:20 UTC, closed without merging